---
- name: Run a script and handle failure using failed_when
  hosts: ftpservers
  become: yes

  tasks:
    - name: Copy the script to the remote host
      copy:
        src: files/check_disk.sh
        dest: /tmp/check_disk.sh
        mode: '0755'

    - name: Execute the script
      command: /tmp/check_disk.sh
      register: script_output
      failed_when: "'DISK OK' not in script_output.stdout"

    - name: Print script output
      debug:
        var: script_output.stdout

