---
- name: Install Apache2 on Ubuntu
  hosts: all
  become: true
  tasks:

    - name: Update APT package list
      apt:
        update_cache: yes

    - name: Install Apache2
      apt:
        name: apache2
        state: present

    - name: Ensure Apache2 is running and enabled
      service:
        name: apache2
        state: started
        enabled: yes

