
---
- name: Installall
  hosts: all
  become: yes  # Run tasks as sudo/root
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install Apache2 package
      apt:
        name: apache2
        state: present

    - name: Ensure Apache2 is started and enabled
      service:
        name: apache2
        state: started
        enabled: yes

    - name: Open port 80 in UFW (optional, if UFW is used)
      ufw:
        rule: allow
        port: '80'
        proto: tcp
      when: ansible_facts['distribution'] == 'Ubuntu'

    - name: Print success message
      debug:
        msg: "Apache2 is successfully installed and running on the node server."

