---
- name: Install Apache2
  hosts: all  # Must match the inventory group name exactly
  become: yes

  tasks:
    - name: Install Apache2
      apt:
        name: apache2
        state: present
        update_cache: yes

